import net.minecraftforge.forge.tasks.Util

plugins {
    id 'net.minecraftforge.licenser' version '1.2.0'
    id 'com.github.ben-manes.versions' version '0.52.0'
    id 'net.minecraftforge.gradleutils' version '3.3.0'
    id 'net.minecraftforge.gitversion' version '3.1.1'
    id 'net.minecraftforge.changelog' version '3.1.2'
    id 'idea'
    id 'eclipse'
    id 'de.undercouch.download' version '5.6.0'
    id 'net.minecraftforge.forgedev' version '7.0.0-beta.0' apply false
    id 'net.minecraftforge.gradlejarsigner' version '1.0.4'
    id 'build-shared' apply false
}

description = 'Root project for MinecraftForge, contains common setup.'
ext.minecraftVersion = gradleutils.unpack(libs.versions.minecraft)
version = gitversion.getMCTagOffsetBranch(minecraftVersion)
ext.forgeVersion = version.substring(minecraftVersion.length() + 1)
ext.minecraftNextVersion = gradleutils.unpack(libs.versions.minecraft.next)
ext.mcpVersion = gradleutils.unpack(libs.versions.mcp)
ext.mappingsChannel = gradleutils.unpack(libs.versions.mappings.channel)
ext.mappingsVersion = gradleutils.unpack(libs.versions.mappings.version)

println "Version: $version"

Util.init() //Init all our extension methods!

changelog {
    from '47.999'
}

tasks.register('setup') {
    dependsOn ':forge:extractMapped'
    if (findProject(':clean'))
        dependsOn ':clean:extractMapped'
}
