plugins {
    id 'java-gradle-plugin'
    id 'groovy'
    id 'idea'
    id 'eclipse'
    alias libs.plugins.licenser
    id 'net.minecraftforge.gradleutils'
}

description = 'Common build logic for Forge and its subprojects.'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

dependencies {
    compileOnly libs.nulls
    compileOnly libs.gradle

    implementation libs.gradleutils.shared
    implementation libs.gradle.download
    implementation libs.forgedev

    implementation libs.bundles.asm
    implementation libs.srgutils
    implementation libs.gson
}

afterEvaluate {
    configurations.api.withDependencies {
        remove(dependencies.gradleApi())
        remove(dependencies.localGroovy())
    }
}

license {
    header = rootProject.file('../LICENSE-header.txt')
    newLine = false
    exclude '**/*.properties'
}

tasks.withType(GroovyCompile).configureEach {
    groovyOptions.optimizationOptions.indy = true
}

gradlePlugin {
    plugins {
        register('forge') {
            id = 'net.minecraftforge.forge.build.forge'
            implementationClass = 'net.minecraftforge.forge.build.BuildForgePlugin'
        }

        register('convention') {
            id = 'net.minecraftforge.forge.build.convention'
            implementationClass = 'net.minecraftforge.forge.build.BuildSharedPlugin'
        }
    }
}
